apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    email: {{ .Values.cert-manager.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          route53:
            region: {{ .Values.cert-manager.route53.region }}
            hostedZoneID: {{ .Values.cert-manager.route53.hostedZoneID }}