apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ (index .Values "cert-manager").serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cert-manager-wrapper.labels" . | nindent 4 }}
