apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ include "chart.fullname" . }}.{{ .Values.global.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "chart.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
