apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "feature-flags-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "feature-flags-api.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.subdomain }}.{{ .Values.global.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  rules:
    - host: {{ .Values.ingress.subdomain }}.{{ .Values.global.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "feature-flags-api.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
