apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    repoURL: https://github.com/shaarron/feature-flags-resources.git
    path: infrastructure/cert-manager
    targetRevision: mulit-env-support
    helm:
      releaseName: cert-manager
      valueFiles:
      - ../../values.yaml
      - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
