apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/shaarron/feature-flags-resources.git
    targetRevision: monitoring-enhancements
    path: infrastructure/mongodb
    helm:
      releaseName: mongodb
      valueFiles:
      - ../../argocd/environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
