apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace | default "efk" }}
spec:
  version: {{ .Values.elasticsearch.version | quote }}
  http:
    tls:
      selfSignedCertificate:
        disabled: {{ .Values.elasticsearch.selfSignedDisabled }}

  nodeSets:
    - name: {{ .Values.elasticsearch.nodeSetName }}
      count: {{ .Values.elasticsearch.nodeCount }}
      config:
        node.store.allow_mmap: {{ .Values.elasticsearch.allowMmap }}
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                {{- toYaml .Values.elasticsearch.resources | nindent 16 }}
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: {{ toYaml .Values.elasticsearch.storage.accessModes | nindent 12 }}
            resources:
              requests:
                storage: {{ .Values.elasticsearch.storage.size }}
