apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feature-flags
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/shaarron/feature-flags-resources.git
    targetRevision: app-of-apps-fixes
    path: applications/feature-flags
    helm:
      releaseName: feature-flags
      valuesFrom:
        - configMap:
            name: helm-values # created by terraform
            namespace: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
