apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
spec:
  project: default
  source:
    repoURL: https://github.com/shaarron/feature-flags-resources.git
    targetRevision: mulit-env-support
    path: infrastructure/efk
    helm:
      releaseName: efk
      valueFiles:
      - ../../argocd/environments/values.yaml
      - ../../argocd/environments/prod/values.yaml


  destination:
    server: https://kubernetes.default.svc
    namespace: efk 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
