# mongodb.yaml
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongo
  namespace: mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "7.0.25"

  security:
    authentication:
      modes: ["SCRAM"]

  users:
    - name: root1
      db: admin
      passwordSecretRef:
        name: mongo-secret
        key: MONGO_INITDB_ROOT_PASSWORD
      scramCredentialsSecretName: mongo-root1-scram-credentials
      roles:
        - name: root
          db: admin

    - name: featureflags
      db: featureflags
      passwordSecretRef:
        name: mongo-secret
        key: APP_USER_PASSWORD
      scramCredentialsSecretName: mongo-app-scram-credentials
      roles:
        - name: readWrite
          db: featureflags
        - name: dbAdmin
          db: featureflags

  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 1Gi
                          
      template:
        spec:
          containers:
            - name: mongod
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "50m"
                limits:
                  memory: "256Mi"
                  cpu: "100m"