apiVersion: v2
name: ingress-nginx
description: Deploys the NGINX Ingress Controller and custom ingress routes
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: ingress-nginx
    version: 4.13.3
    repository: "https://kubernetes.github.io/ingress-nginx"
