targetRevision: main
env: prod
global:
  host: "sharon-k.com"

feature-flags-api:
  image:
    tag: v1.0.19
  ingress:
    subdomain: "backend"

mongodb:
  mongo:
    members: 3

kibana:
  config:
    server.publicBaseUrl: "https://kibana.sharon-k.com"
  ingress:
    hosts:
      - host: kibana.sharon-k.com
        paths:
          - path: /

grafana:
  ingress:
    hosts:
      - grafana.sharon-k.com
