apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kube-prometheus-stack.fullname" . }}-feature-flags-api-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-prometheus-stack.labels" . | nindent 4 }}
    app: feature-flags-api
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: feature-flags-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
