# mongo-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD: cm9vdDE=
  MONGO_INITDB_ROOT_USERNAME: cm9vdDE=
  APP_USER_PASSWORD: YXBw
