# Only create this if external secrets are DISABLED
{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongo.secretName | default "mongo-secret" }}
  labels:
    app.kubernetes.io/name: mongodb
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD:  {{ randAlphaNum 20 | b64enc | quote }}
  APP_USER_PASSWORD: {{ randAlphaNum 20 | b64enc | quote }}
{{- end }}