apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterSecretStore.name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.clusterSecretStore.syncWave | quote }}
spec:
  provider: 
    aws:
      service: {{ .Values.clusterSecretStore.provider.aws.service }}
      region: {{ .Values.clusterSecretStore.provider.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
            namespace: {{ .Values.serviceAccount.namespace }}
