targetRevision: main # example: can be some dev branch
env: dev
global:
  env: dev
  host: "dev.sharon-k.com"

feature-flags-api:
  image:
    tag: dev-a721654
  ingress:
    subdomain: "backend"

mongodb:
  mongo:
    members: 1

kibana:
  config:
    server.publicBaseUrl: "https://kibana.dev.sharon-k.com"
  ingress:
    hosts:
      - host: kibana.dev.sharon-k.com
        paths:
          - path: /

grafana:
  ingress:
    hosts:
      - grafana.dev.sharon-k.com
