apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:shaarron/feature-flags-resources.git
    targetRevision: main
    path: helm/observability/kps
    helm:
      valueFiles:
        - values.yaml                
  destination:
    server: https://kubernetes.default.svc
    namespace: kps                  
  dependsOn:
    - prometheus-crds               
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true