env: staging
global:
  host: "staging.sharon-k.com"
api:
  image:
    tag: rc-3c7b3f4
kibana:
  config:
    server.publicBaseUrl: "https://kibana.staging.sharon-k.com"
mongodb:
  mongo:
    members: 3
