targetRevision: main
env: staging
global:
  env: staging
  host: "staging.sharon-k.com"

feature-flags-api:
  image:
    tag: rc-3c7b3f4
  ingress:
    subdomain: "backend"

mongodb:
  mongo:
    members: 3

kibana:
  config:
    server.publicBaseUrl: "https://kibana.staging.sharon-k.com"
  ingress:
    hosts:
      - host: kibana.staging.sharon-k.com
        paths:
          - path: /

grafana:
  ingress:
    hosts:
      - grafana.staging.sharon-k.com
