apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" 
spec:
  project: default
  source:
    repoURL: https://github.com/shaarron/feature-flags-resources.git
    targetRevision: main
    path: infrastructure/efk
    helm:
      releaseName: efk
      values: |
        global:
          host: its-sharon.com
  destination:
    server: https://kubernetes.default.svc
    namespace: efk 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
