apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"     # deploys after operators, before app
spec:
  project: default
  source:
    repoURL: git@github.com:shaarron/feature-flags-resources.git
    targetRevision: argo-app-set
    path: infrastructure/efk
    helm:
      releaseName: efk
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: efk 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
