apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-setup
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/shaarron/feature-flags-resources.git
    targetRevision: app-of-apps-fixes
    path: infrastructure/external-secrets-setup
    helm:
      valueFiles:
      - ../../argocd/applications/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
