apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-staging
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/shaarron/feature-flags-resources.git
    targetRevision: main
    path: argocd/environments/staging
    directory:
      recurse: true
    
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

