apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/shaarron/feature-flags-resources.git
    targetRevision: feature/app-of-apps-fixes
    path: argocd/applications 
    directory:
      recurse: true
    helm:
      valuesFrom:
        - configMap:
            name: helm-values  # Created by Terraform
            namespace: argocd

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
