apiVersion: v2
name: cert-manager
description: Cert Manager Helm chart
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- condition: cert-manager.enabled
  name: cert-manager
  repository: https://charts.jetstack.io
  version: v1.16.2
