apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace | default "efk" }}
spec:
  version: {{ .Values.elasticsearch.version | quote }}
  http:
    {{- toYaml .Values.elasticsearch.http | nindent 4 }}

  nodeSets:
    - name: {{ .Values.elasticsearch.nodeSetName }}
      count: {{ .Values.elasticsearch.nodeCount }}
      config:
        {{- toYaml .Values.elasticsearch.config | nindent 8 }}
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                {{- toYaml .Values.elasticsearch.resources | nindent 16 }}
              # readinessProbe:
              #   {{- toYaml .Values.elasticsearch.readinessProbe | nindent 16 }}
              # livenessProbe:
              #   {{- toYaml .Values.elasticsearch.livenessProbe | nindent 16 }}
      volumeClaimTemplates:
        {{- toYaml .Values.elasticsearch.volumeClaims | nindent 8 }}
