apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: {{ .Values.namespace | default "efk" }}
spec:
  version: {{ .Values.kibana.version | quote }}
  count: {{ .Values.kibana.count }}
  elasticsearchRef:
    name: {{ .Values.kibana.elasticsearchRef }}
  
  config:
    {{- toYaml .Values.kibana.config | nindent 4 }}

  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            {{- toYaml .Values.kibana.resources | nindent 12 }}