apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 9.1.5
  count: 1
  elasticsearchRef:
    name: elasticsearch
  config:
    xpack.security.secureCookies: false
    server.publicBaseUrl: "http://kibana.its-sharon.com"

  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              memory: "2Gi"