apiVersion: v2
name: efk
description: EFK (Elasticsearch, Fluent Bit, Kibana) observability stack
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: fluent-bit
    version: 0.54.0
    repository: "https://fluent.github.io/helm-charts"
