global:
  domain: sharon-k.com

api:
  image:
    repository: ghcr.io/shaarron/feature-flags-app/feature-flags-api
    tag: latest # default tag unless overridden by environment-specific values.yaml

clusterSecretStore:
  provider:
    aws:
      region: "ap-south-1"

ingress:
  tlsSecretName: "wildcard-sharon-k"

certManagerConfig:
  email: "sharon@sharon-k.com"
  route53:
    region: "ap-south-1"
    hostedZoneID: "Z10244981ZAMIY8KVE0M3"
  wildcardCert:
    secretName: "wildcard-sharon-k"

external-dns:
  domainFilters:
    - "sharon-k.com"
