hostedZoneID: "Z01921003NQMEIE6Q3E0L"

feature-flags-api:
  image:
    repository: ghcr.io/shaarron/feature-flags-app/feature-flags-api
    tag: latest # default tag unless overridden by environment-specific values.yaml

clusterSecretStore:
  provider:
    aws:
      region: "ap-south-1"

ingress:
  tlsSecretName: "wildcard-sharon-k"

certManagerConfig:
  domain: "sharon-k.com"
  email: "sharon@sharon-k.com"
  route53:
    region: "ap-south-1"
    hostedZoneID: "Z01921003NQMEIE6Q3E0L"
  wildcardCert:
    secretName: "wildcard-sharon-k"